export enum RiskCaseResolutionAction {
  MarkRiskCaseUnderReviewAfterSubcaseCompletion = "MarkRiskCaseUnderReviewAfterSubcaseCompletion",
  MarkRiskCaseResolvedAfterSubcaseCompletion = "MarkRiskCaseResolvedAfterSubcaseCompletion",
  MarkRiskCaseManualInterventionRequiredAfterSubcaseFailure = "MarkRiskCaseManualInterventionRequiredAfterSubcaseFailure"
}
